spring.application.name=discord-bot

discord.token=${DISCORD_TOKEN}
discord.welcome-channel-id=${DISCORD_WELCOME_CHANNEL_ID}
discord.greetings-channel-id=${DISCORD_GREETINGS_CHANNEL_ID}
discord.guild-id=${DISCORD_GUILD_ID}

discord.panikmode-practice-channel=${DISCORD_PRACTICE_CHANNEL_ID}
discord.panikmode-tag=${DISCORD_PANIKMODE_TAG_ID}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update